### PR TITLE
Module list

### PR DESCRIPTION
**Pull request by spasarok**
Adding a module list command

### CODE REVIEW

**Comment by oconnor663** [comment]
@olson-sean-k, @spasarok and I paired this one. What do you think of the name?

**Comment by olson-sean-k** [comment]
Name looks good to me. Do we want this to support a `--json` option too?

**Comment by oconnor663** [comment]
I think we'll grab that one in a subsequent PR. I'll merge this one.

**Comment by oconnor663** [comment]
Or rather, I would except we have a lint error that's breaking CI. @spasarok, if you run `test.sh` you should be able to see the same thing. Could you fix that one before we merge?

**Comment by oconnor663** [comment]
I merged this and put the lint fix on top of it.

**Pull request merged**
